[package]
name = "hirola"
version = "0.1.3"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
description = "A html library for building client side webapps"
repository = "https://github.com/geofmureithi/hirola"
documentation = "https://docs.rs/hirola"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["wasm", "html", "dom", "web"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hirola-core = { path = "crates/hirola-core", version = "0.1.3" }
hirola-macros = { path = "crates/hirola-macros", version = "0.1.3" }
matchit = "0.6"
anymap = "1.0.0-beta.2"
wasm-bindgen = { version = "0.2.79" }
wasm-bindgen-futures = { version = "0.4.29" }


[dependencies.web-sys]
features = [
    "console",
    "Comment",
    "Document",
    "DocumentFragment",
    "DomTokenList",
    "Element",
    "Event",
    "EventSource",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlCollection",
    "Node",
    "NodeList",
    "Text",
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
    "Location",
    "History",
    "CanvasRenderingContext2d",
    "HtmlCanvasElement"
]
version = "0.3.56"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[workspace]
members = [
    "crates/hirola-core",
    "crates/hirola-macros",
    "examples/counter",
    "examples/todo",
    "examples/canvas"
]


[package.metadata.docs.rs]
all-features = true
default-target = "wasm32-unknown-unknown"

[profile.release]
# Do not perform backtrace for panic on release builds.
panic = 'abort'
# Perform optimizations on all codegen units.
codegen-units = 1
# Optimize for size.
opt-level = 'z' # or 'z' to optimize "aggressively" for size
# Enable link time optimization.
lto = true
