[package]
name = "hirola"
version = "0.1.6"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
description = "A html library for building client side webapps"
repository = "https://github.com/geofmureithi/hirola"
documentation = "https://docs.rs/hirola"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["wasm", "html", "dom", "web"]
edition = "2021"


[features]
default = ["tracing"]
## Support Tracing 👀
tracing = []
## Add Form Mixins
form = ["hirola-form"]

[dependencies]
hirola-core = { path = "crates/hirola-core", version = "0.1.6" }
hirola-macros = { path = "crates/hirola-macros", version = "0.1.6" }
hirola-form = { path = "crates/hirola-form", version = "0.1.6", optional = true }
wasm-bindgen = { version = "0.2.79" }

[dependencies.web-sys]
features = [
    "console",
    "Element",
    "Event",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlCollection",
    "Node",
    "NodeList",
    "Text",
    'Window',
    "History",
]
version = "0.3.56"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[workspace]
members = [
    "crates/hirola-core",
    "crates/hirola-macros",
    "crates/hirola-form",
    "examples/counter",
    "examples/todo",
    "examples/canvas",
    "examples/fake-api",
    "examples/chartjs",
    "examples/x-for",
    "examples/mixin",
    "examples/form"
]


[package.metadata.docs.rs]
all-features = true
default-target = "wasm32-unknown-unknown"
