[package]
name = "hirola"
version = "0.1.3-alpha.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
description = "An html library for building client side webapps"
repository = "https://github.com/geofmureithi/hirola"
documentation = "https://docs.rs/hirola"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["wasm", "html", "dom", "web"]
edition = "2018"

[dependencies]
hirola-core = { path = "crates/hirola-core", version = "0.1.3-alpha.0" }
hirola-macros = { path = "crates/hirola-macros", version = "0.1.0" }
matchit = "0.6"
anymap = "0.12"
wasm-bindgen = { version = "0.2.79" }
wasm-bindgen-futures = { version = "0.4.29" }


[dependencies.web-sys]
features = [
    "console",
    "Comment",
    "Document",
    "DocumentFragment",
    "DomTokenList",
    "Element",
    "Event",
    "EventSource",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlCollection",
    "Node",
    "NodeList",
    "Text",
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
    "Location",
    "History",
    "CanvasRenderingContext2d",
    "HtmlCanvasElement"
]
version = "0.3.56"

[workspace]
members = [
    "crates/hirola-core",
    "crates/hirola-macros",
    "examples/counter",
    "examples/todo",
    "examples/canvas"
]


[package.metadata.docs.rs]
all-features = true
default-target = "wasm32-unknown-unknown"