[package]
name = "hirola-macros"
version = "0.1.1"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
syn = { version = "1", features = ["full"] }
quote = { package = "quote", version = "1.0.3" }
proc-macro2 = "1.0"
proc-macro-hack = "0.5.2"
