[package]
name = "hirola-core"
version = "0.1.5"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2021"
description = "An html library for building client side webapps"
repository = "https://github.com/geofmureithi/hirola"
documentation = "https://docs.rs/hirola"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
keywords = ["wasm", "html", "dom", "web"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
chrono = {version = "0.4", features = ["wasmbind"]}
html-escape = {version = "0.2.7", optional = true}
hirola-macros = {path = "../hirola-macros", version = "0.1.3"}
ref-cast = "1.0"
serde = {version = "1.0", optional = true}
wasm-bindgen = {version = "0.2", optional = true}

[dependencies.web-sys]
features = [
  "console",
  "Comment",
  "Document",
  "DocumentFragment",
  "Element",
  "Event",
  "HtmlElement",
  "Node",
  "Text",
  "Window",
]
optional = true
version = "0.3"

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}
wasm-bindgen-test = "0.3"

[features]
default = ["dom", "wasm-bindgen", "web-sys"]
dom = []
ssr = ["html-escape", "web-sys/Event"]

[[bench]]
harness = false
name = "reactivity"

[[bench]]
harness = false
name = "ssr"

[[test]]
name = "ssr"
required-features = ["ssr"]

[package.metadata.docs.rs]
all-features = true
default-target = "wasm32-unknown-unknown"
